// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace FromZeroToHero.Models.ContentTypes
{
    public partial class ProductExampleContentType
    {
        public const string Codename = "product_example_content_type";
        public const string DescriptionCodename = "description";
        public const string ImageCodename = "image";
        public const string NameCodename = "name";
        public const string TaxonomyCategorizingTargetAudienceCodename = "taxonomy___categorizing_target_audience";
        public const string UrlCodename = "url";

        public string Description { get; set; }
        public IEnumerable<IAsset> Image { get; set; }
        public string Name { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public IEnumerable<ITaxonomyTerm> TaxonomyCategorizingTargetAudience { get; set; }
        public string Url { get; set; }
    }
}